# SITE CONFIGURATION
title: Jhuei Yummy # your site title
author: Jhuei # You :P
description: > # Meta description of Homepage
  Share the coding issues and solution :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jhuei.com" # the base hostname & protocol for your site, e.g. http://example.com
image: assets/img/icons/android-chrome-256x256.png
#Language
lang: zh-Hant-TW
words_per_minute: 50
# SEO PLUGIN
social:
  name: jhuei
  links:
    # - https://twitter.com/BenBalter
    # - https://www.facebook.com/ben.balter
    # - https://www.linkedin.com/in/BenBalter
    # - https://plus.google.com/+BenBalter
    # - https://github.com/benbalter
    # - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: '<img src="\assets\img\icons\home.png" alt="HOME">', link: '/'}
  - {name: '<img src="\assets\img\icons\about.png" alt="ABOUT">', link: '/about'}
  - {name: '<img src="\assets\img\icons\archives.png" alt="ARCHIVES">', link: '/archives'}
  - {name: '<img src="\assets\img\icons\search.png" alt="SEARCH">', link: '/search'}
  - {name: '<img src="\assets\img\icons\contact.png" alt="CONTACT">', link: '/contact'}

tagline: >
  Want to learn fried chicken? Teach you!
# Index banner
hero_img: posts/banner.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
background_img: posts/background.JPG # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

#Formspree
email: mvobleyb # email for form submission

logo_size: 30px

# Footer icons
RSS: true
twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:   # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer
facebook_username:  # replace with facebook_username or comment to remove link from footer

# Comment
comment: false #to enable comment
disqus:
  shortname: jhuei # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-M9CWRJT # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: false
excerpt_separator: <!--more-->

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null or rouge
# theme: jekyll-jhuei # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

jekyll-archives:
  enabled: [all]
  layout: page
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/page:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

compress_html:
  clippings: all

jekyll_admin:
  hidden_links:
    # - admin
    # - posts
    # - pages
    # - staticfiles
    # - datafiles
    # - configuration

plugins:
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin
  - jemoji
  - wdm
